### PR TITLE
[RFR] Winning condition is active

### PR DESCRIPTION
**Pull request by JulienMattiussi**
https://trello.com/c/3DpQL74X

WARNING : Database has changed

Game display message when a player win (and the board locks)
Some tests writtens

image

### CODE REVIEW

**Comment by alexisjanvier** [comment]
PR #4  has been merged, you can make a rebase.

**Review by alexisjanvier — CHANGES_REQUESTED** [review]
You should start setting up some functional tests.
https://symfony.com/doc/current/testing.html#functional-tests
https://symfony.com/doc/current/best_practices/tests.html#functional-tests

And don't hesitate to make a rebase on master to facilitate the code review.

**Review by alexisjanvier — CHANGES_REQUESTED** [review]
I really don't like this `GameApi` class and of all its static methods. Let's talk in the morning.

**Comment by alexisjanvier** [comment]
And also, you should add a recipe for migration in the makefile

**Comment by jdemangeon** [comment]
I've adviced @JulienMattiussi to use static functions instead of a instance methods ones because functions can be used individually and he didn't succeed to setup functions without classes.

I agree we should look into that...

**Review by alexisjanvier — APPROVED** [review]

**Pull request merged**
